# Generated by Django 4.2 on 2023-05-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('identificacion', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('tipo_boleto', models.CharField(choices=[('general', 'General'), ('palcos', 'Palcos'), ('preferencial', 'Preferencial')], max_length=20)),
            ],
        ),
    ]
