# Generated by Django 4.2 on 2023-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='nombre_evento',
            field=models.CharField(default='sin evento', max_length=250),
        ),
    ]
